-- +goose Up
CREATE TABLE IF NOT EXISTS USERS(
    ID SERIAL NOT NULL PRIMARY KEY,
    EMAIL TEXT NOT NULL UNIQUE,
    PASSWORD_HASH BYTEA NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL);

CREATE INDEX IF NOT EXISTS idx_email on users(email);

CREATE TABLE IF NOT EXISTS PERSONAL_DATA(
    ID SERIAL PRIMARY KEY,
    PDATA TEXT NOT NULL,
    USER_ID INT NOT NULL,
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL);

-- +goose Down
-- +goose StatementBegin
DROP TABLE PERSONAL_DATA;
DROP TABLE USERS;
-- +goose StatementEnd
